### ISSUE TITLE
dependency on symfony/symfony ?

### ISSUE THREAD

**Issue by dbu** [facile-it/symfony-functional-testcase#1]
composer.json lists symfony/symfony as dependency. i think it should instead depend on the actual components that are really needed. i am not even sure whether framework-bundle and request should be dependencies of this. if somebody wants to test, they need to depend on framework / request anyways - having that dependency pulled in through the require-dev for functional test case could hide a dependency management mistake.

you might split this into a WebTestCase and a CommandTestCase so that e.g. the web test case works even when no command package is around. 
the WebTestCase should depend on HttpKernel Client, not on FrameworkBundle Client - it does not require any of the framework client additions as far as i can see.

**Comment by Jean85** [comment]
I currently do not require the whole `symfony/symfony` package, if not in the dev section for testing:

https://github.com/facile-it/symfony-functional-testcase/blob/master/composer.json#L22-L27

BTW splitting it would require another fork... I'm not sure it would be a good trade off.

**Comment by dbu** [comment]
oh, i misread that. yep, its in require-dev.
